---
설명: try, throws, do, catch
---
> [!important] 에러를 던질 수 있는(실패할 수 있는) Throwing Function을 실행시키기 위해서는 에러 핸들링이 필요!

  

### `try` - `do`, `catch` 를 사용하는 방법

```Swift
func tryExample() {
		do {
				let url = URL(string: "https://www.naver.com")!
				let data = try Data(contentsOf: url)
				let fileContents = String(data: data, encoding: .utf8)
				print(fileContents)
		} catch {
				print(error)
		}
}
```

  

### `do`, `catch` 대신 `옵셔널 try`를 사용하는 방법

```Swift
func tryExample2() {
		let url = URL(string: "https://www.naver.com")!
		guard let data = try? Data(contentsOf: url) else { return }
		let fileContents = String(data: data, encoding: .utf8)
		print(fileContents)
}
```

  

### 혹은, Error 책임 전가 (Error Propagation)

```Swift
func tryExample3() throws {
		let url = URL(string: "https://www.naver.com")!
		let data = try Data(contentsOf: url)
		let fileContents = String(data: data, encoding: .utf8)
		print(fileContents)
}


//try! tryExample3()

do {
		tryExample3()
} catch { }
```